name: "Setup environment"
description: "Setups the environment for CI jobs"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'
    
    - name: Cache venv
      id: cache-venv
      uses: actions/cache@v3
      with:
        key:
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
        path: 
          ./venv

    - run: | 
        which python
        which pip 
        python -V
        pip install -r requirements.txt
        python -m venv venv
        source venv/bin/activate
        which python
      shell: bash
      if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
