name: "Setup environment"
description: "Setups the environment for CI jobs"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'
        cache: pip
      
    - run: | 
        which python
        which pip 
        python -V
        pip install -r requirements.txt
        python -m venv venv
        source venv/bin/activate
        which python
      shell: bash
